[package]
name = "collaborate-core"
version = "0.1.0"
edition = "2024"

[dependencies]
scylla = "0.12" # Check for the latest version on crates.io
tokio = { version = "1", features = ["full"] }
anyhow = "1.0" # For easier error handling

[[bin]]
name = "main"
path = "main.rs"
