services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-dev
    ports:
      - "26257:26257" # CockroachDB SQL port
      - "8080:8080"   # CockroachDB Admin UI port
    command: "start-single-node --insecure --advertise-addr=localhost"
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    healthcheck:
      # Checks if the node is ready to accept connections via the HTTP health endpoint
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s # Grace period for CockroachDB to start

volumes:
  cockroach_data: