services:
  scylladb:
    image: scylladb/scylla:latest
    container_name: scylla-dev # As per your original request
    ports:
      - "9042:9042" # Maps port 9042 on your host to port 9042 in the container
    command: "--smp 1 --memory 1G --developer-mode 1"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s   # How often to run the check
      timeout: 10s    # How long to wait for the check to return
      retries: 10     # How many times to retry before marking as unhealthy
      start_period: 30s # Grace period for startup before failures count

  scylla-init:
    image: scylladb/scylla:latest # Use the same ScyllaDB image as it contains cqlsh
    container_name: scylla-init # Friendly name for the init container
    depends_on:
      scylladb:
        condition: service_healthy # Crucial: waits for scylladb to be healthy
    volumes:
      - ./init-db.cql:/init-db.cql # Mount the CQL script into the container
    entrypoint: /bin/sh
    command: -c "
          cqlsh scylladb -f /init-db.cql
      "
